import type { NextPage } from 'next';
import Head from 'next/head';
import TestComponent from '../components/TestComponent';

import styles from '../styles/Main.module.scss';

const Home: NextPage = () => {
  return (
    <div className={styles.mainContainer}>
			<Head>
				<title>sampleText</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main>
    		<TestComponent />
			</main>
    </div>
  );
};

export default Home;
